#!/usr/bin/env bash

if [[ -f "/usr/bin/optirun" ]]; then
    optirun -b primus --failsafe mpv --msg-level=all=error:statusline=status "$@"
else
    mpv --msg-level=all=error:statusline=status "$@"
fi

