#!/bin/sh

get_urls () {
    tmux capture-pane -J
    tmux show-buffer | xurls | tac | dmenu -b -l 10
}

follow () {
    get_urls | xargs -r "${BROWSER}" # 9 plumb
}

grab () {
    get_urls | xargs -r | xsel -i
}

if [[ "$1" == "-g" ]]; then
    grab
else
    follow
fi
