#!/bin/sh

get_urls () {
    tmux capture-pane -J
    tmux show-buffer | xurls | tac | bemenu -b -l 10
}

follow () {
    get_urls | xargs -r "${BROWSER}" > /dev/null # 9 plumb
}

grab () {
    get_urls | xargs -r | xclip -i
}

if [[ "$1" == "-g" ]]; then
    grab
else
    follow
fi
