#!/usr/bin/env bash

export QEMU_AUDIO_DRV=pa

pushd "$HOME/prj/vms/$1"

args=("$@")

qemu-system-x86_64 -m 4G \
    -drive file=./disk.img,index=0,media=disk,format=raw \
    -enable-kvm -cpu host -soundhw hda \
    -net nic -net user,smb=/home/halosghost/prj/vms/shared "${args[@]:1}"
