#!/usr/bin/env bash

[[ -z "$IFACE"       ]] && IFACE=wlp3s0
[[ -z "$WPA_SUPFILE" ]] && WPA_SUPFILE="/etc/wpa_supplicant/wpa_supplicant-$IFACE.conf"

case "$1" in
    add)    wpa_passphrase "$2" "$3" | sudo tee -a "${4:-$WPA_SUPFILE}" > /dev/null;;
    scan)   sudo iw dev "${2:-$IFACE}" scan | awk "/SSID: $3/";;
    reload) sudo killall -HUP wpa_supplicant;;
esac
